// Code generated by Slice Machine. DO NOT EDIT.

import ContactDetails from './ContactDetails/index.svelte';
import HomeHeader from './HomeHeader/index.svelte';
import Mission from './Mission/index.svelte';

export const components = {
	contact_details: ContactDetails,
	home_header: HomeHeader,
	mission: Mission
};
